name: ludmigo
recipe: laravel
config:
  php: '8.4'
  webroot: public
  composer_version: 2-latest
  env_file:
    - .env

#excludes:
#  - vendor
#  - node_modules

# Access
proxy:
  appserver:
  - ludmigo.lndo.site
  mailhog:
  - mail.ludmigo.lndo.site
  pma:
  - pma.ludmigo.lndo.site

# Add in phpmyadmin
services:
  # Add a phpmyadmin db frontend
  pma:
    # Use the latest version of phpmyadmin
    type: phpmyadmin

    # The databases you want to look at, this will default to a service called
    # "database"
    #
    # You might want to run `lando info` on your app to see what databases you
    # have available
    hosts:
      - database
  mailhog:
      type: mailhog
      hogfrom:
        - appserver
  node:
    type: node:22
    ports:
      - 5173:5173
tooling:
  npm:
    service: node
  node:
    service: node


